#!/bin/bash
echo "set permissions"
chmod -R 777 bootstrap/cache
chmod -R 777 storage

if [ ! -d vendor ]; then
    echo "create vendors"
    composer install
fi

if [ ! -d node_modules ]; then
    echo "create node_modules"
    npm install
fi

npm run dev

if [ ! -f .env ]; then
    echo "create .env file"
    cp .env.example .env
fi
if [ ! -f .htaccess ]; then
    echo "create .htaccess file"
    cp htaccess.tpl .htaccess
fi
# check for APP_KEY
appKey=$(grep ^APP_KEY .env|awk -F "=" '{print $2}')
if [ "$appKey" == "" ]; then
    echo "no APP_KEY found, will generate the key"
    php artisan key:generate
else
    echo "APP_KEY seems to be valid: $appKey"
fi

echo "generate Model-Classes: Author, Movie, Todo if not exist"
if [ ! -f app/Models/Author.php ]; then
	php artisan make:model Author
fi
if [ ! -f app/Models/Movie.php ]; then
	php artisan make:model Movie
fi
if [ ! -f app/Models/Todo.php ]; then
	php artisan make:model Todo
fi
git add app/Models/*

echo "migrate database tables"
php artisan migrate

echo "seed database data"
php artisan db:seed

echo "clear all caches"
php artisan cache:clear
php artisan config:clear
php artisan route:clear
php artisan view:clear
printf 'all done \360\237\230\216\n'
